## Código completo para puxar dados da Enel 2021

Importando bibliotecas

In [1]:
import pandas as pd
import ssl

Código retirado da internet para resolver um problema de SSL

In [2]:
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

Parâmetros chaves para a consulta

In [3]:
ano = 2021
distribuidora = 383
nome_distribuidora = 'Enel/RJ'

## Mês 1

In [4]:
mes = 1

 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

Realizando o scrap com base no link e parâmetros passados anteriormente

In [5]:
scrap = pd.read_html(url)

Criando o DataFrame do mês 1

In [6]:
df1 = pd.DataFrame(scrap[0])

O DF vem com linhas desnecessárias para o que é desejado com essa extração, por isso são removidas as últimas 3 linhas e as 2 primeiras. A linha superior que sobra vira cabeçalho apenas no mês 1, importante remover essa linha na consulta dos meses seguintes

In [7]:
df1.drop(df1.tail(3).index,inplace=True) # Foi passado como localização as últimas 3 linhas e o inplace é para fazer alteração direto no DF original

In [8]:
df1.drop(df1.head(2).index,inplace=True)

Transformando a primeira linhha em cabeçalho

In [9]:
new_header = df1.iloc[0] # Pega os items da primeira linha e adciona à váriavel new_header
df1 = df1[1:] # Retorna todo o dataframe a partir da linha 1 (sem a linha 0 que será cabeçalho)
df1.columns = new_header # defininindo o nome das colunas conforme a lista presente no "new_header"

As próximas linhas de código incluem colunas que serão importantes posteriormente

In [10]:
df1 = df1.assign(MES = '{}'.format(mes))

In [11]:
df1 = df1.assign(ANO = '{}'.format(ano))

In [12]:
df1 = df1.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [13]:
df1 = df1.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [14]:
df1

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,68.771,071,033,000,000,000,000,006,...,000,000,000,000,000,000,1,2021,Enel/RJ,383
4,Angra dos Reis,13016,44.194,091,076,000,000,000,000,007,...,000,000,000,000,000,000,1,2021,Enel/RJ,383
5,Araruama,13017,26.407,110,046,000,000,000,000,004,...,000,000,000,000,000,000,1,2021,Enel/RJ,383
6,Arraial do Cabo,13019,15.086,063,020,000,000,000,000,010,...,000,000,000,000,000,000,1,2021,Enel/RJ,383
7,Arsenal,13020,51.821,058,069,000,000,003,049,007,...,000,000,000,000,000,000,1,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,28.008,078,065,000,000,001,019,000,...,001,000,000,000,000,000,1,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.149,223,073,000,000,000,000,001,...,000,000,000,000,000,000,1,2021,Enel/RJ,383
82,Bom Jardim,16393,21.616,148,051,000,000,000,000,005,...,000,000,000,000,000,000,1,2021,Enel/RJ,383
83,Retiro Saudoso,16394,60.827,064,031,000,000,000,000,003,...,002,000,000,000,000,000,1,2021,Enel/RJ,383
84,Areal,16395,21.401,277,101,000,000,000,000,031,...,004,001,000,000,000,000,1,2021,Enel/RJ,383

## Agora será realizada as consultas dos meses seguintes e a concatenação de DataFrames

## Mês 2

In [15]:
mes = 2
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [16]:
scrap = pd.read_html(url)

In [17]:
df2 = pd.DataFrame(scrap[0])

In [18]:
df2.drop(df2.tail(3).index,inplace=True)

In [19]:
df2.drop(df2.head(2).index,inplace=True)

In [20]:
new_header = df2.iloc[0] # Pega os items da primeira linha e adciona à váriavel new_header
df2 = df2[1:] # Retorna todo o dataframe a partir da linha 1 (sem a linha 0 que será cabeçalho)
df2.columns = new_header # defininindo o nome das colunas conforme a lista presente no "new_header"

In [21]:
df2 = df2.assign(MES = '{}'.format(mes))

In [22]:
df2 = df2.assign(ANO = '{}'.format(ano))

In [23]:
df2 = df2.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [24]:
df2 = df2.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [25]:
df2

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,68.914,059,017,000,000,000,000,002,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
4,Angra dos Reis,13016,44.096,078,038,000,000,000,000,004,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
5,Araruama,13017,26.451,105,125,000,000,000,000,001,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
6,Arraial do Cabo,13019,15.140,057,030,000,000,000,000,006,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
7,Arsenal,13020,51.850,149,093,000,000,000,000,005,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,28.236,092,059,000,000,015,037,002,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.176,468,116,000,000,000,000,004,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
82,Bom Jardim,16393,21.663,197,142,000,000,000,000,004,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
83,Retiro Saudoso,16394,60.940,040,028,000,000,000,000,012,...,000,000,000,000,000,000,2,2021,Enel/RJ,383
84,Areal,16395,21.425,617,188,000,000,000,000,022,...,000,000,000,000,000,000,2,2021,Enel/RJ,383

## Mês 3

In [26]:
mes = 3
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [27]:
scrap = pd.read_html(url)

In [28]:
df3 = pd.DataFrame(scrap[0])

In [29]:
df3.drop(df3.tail(3).index,inplace=True)

In [30]:
df3.drop(df3.head(2).index,inplace=True)

In [31]:
new_header = df3.iloc[0] # Pega os items da primeira linha e adciona à váriavel new_header
df3 = df3[1:] # Retorna todo o dataframe a partir da linha 1 (sem a linha 0 que será cabeçalho)
df3.columns = new_header # defininindo o nome das colunas conforme a lista presente no "new_header"

In [32]:
df3 = df3.assign(MES = '{}'.format(mes))

In [33]:
df3 = df3.assign(ANO = '{}'.format(ano))

In [34]:
df3 = df3.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [35]:
df3 = df3.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [36]:
df3

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,68.890,060,032,000,000,000,000,004,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
4,Angra dos Reis,13016,44.201,239,103,000,000,000,000,007,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
5,Araruama,13017,26.474,210,092,000,000,000,000,002,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
6,Arraial do Cabo,13019,15.141,145,050,000,000,000,000,006,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
7,Arsenal,13020,51.956,078,025,000,000,000,000,000,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,28.375,086,094,000,000,001,024,005,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.226,400,161,000,000,000,000,001,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
82,Bom Jardim,16393,21.723,577,173,000,000,000,000,006,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
83,Retiro Saudoso,16394,60.965,130,057,000,000,001,000,013,...,000,000,000,000,000,000,3,2021,Enel/RJ,383
84,Areal,16395,21.446,303,094,000,000,000,000,008,...,000,000,000,000,000,000,3,2021,Enel/RJ,383

## Mês 4

In [37]:
mes = 4
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [38]:
scrap = pd.read_html(url)

In [39]:
df4 = pd.DataFrame(scrap[0])

In [40]:
df4.drop(df4.tail(3).index,inplace=True)

In [41]:
df4.drop(df4.head(2).index,inplace=True)

In [42]:
new_header = df4.iloc[0] # Pega os items da primeira linha e adciona à váriavel new_header
df4 = df4[1:] # Retorna todo o dataframe a partir da linha 1 (sem a linha 0 que será cabeçalho)
df4.columns = new_header # defininindo o nome das colunas conforme a lista presente no "new_header"

In [43]:
df4 = df4.assign(MES = '{}'.format(mes))

In [44]:
df4 = df4.assign(ANO = '{}'.format(ano))

In [45]:
df4 = df4.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [46]:
df4 = df4.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [47]:
df4

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,68.860,042,021,000,000,000,000,003,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
4,Angra dos Reis,13016,44.380,062,060,000,000,000,000,007,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
5,Araruama,13017,26.586,203,040,000,000,000,000,002,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
6,Arraial do Cabo,13019,15.126,132,022,000,000,000,000,008,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
7,Arsenal,13020,51.971,052,027,000,000,000,000,008,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,28.482,051,037,000,000,000,000,002,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.242,051,011,000,000,000,000,004,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
82,Bom Jardim,16393,21.738,108,053,000,000,000,000,003,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
83,Retiro Saudoso,16394,61.164,039,014,000,000,000,000,011,...,000,000,000,000,000,000,4,2021,Enel/RJ,383
84,Areal,16395,21.602,268,069,000,000,000,000,011,...,000,000,000,000,000,000,4,2021,Enel/RJ,383

## Mês 5

In [48]:
mes = 5
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [49]:
scrap = pd.read_html(url)

In [50]:
df5 = pd.DataFrame(scrap[0])

In [51]:
df5.drop(df5.tail(3).index, inplace = True)

In [52]:
df5.drop(df5.head(2).index, inplace = True)

In [53]:
new_header = df5.iloc[0]
df5 = df5[1:]
df5.columns = new_header

In [54]:
df5 = df5.assign(MES = '{}'.format(mes))

In [55]:
df5 = df5.assign(ANO = '{}'.format(ano))

In [56]:
df5 = df5.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [57]:
df5 = df5.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [58]:
df5

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,68.465,059,016,000,000,000,000,005,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
4,Angra dos Reis,13016,44.363,048,048,000,000,000,000,005,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
5,Araruama,13017,26.528,040,010,000,000,000,000,005,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
6,Arraial do Cabo,13019,15.094,044,015,000,000,000,000,012,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
7,Arsenal,13020,51.717,078,028,000,000,000,000,004,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,28.332,168,113,000,000,000,000,005,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.223,040,018,000,000,000,000,001,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
82,Bom Jardim,16393,21.747,194,126,000,000,000,000,008,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
83,Retiro Saudoso,16394,61.172,052,019,000,000,000,000,023,...,000,000,000,000,000,000,5,2021,Enel/RJ,383
84,Areal,16395,21.602,172,063,000,000,000,000,024,...,000,000,000,000,000,000,5,2021,Enel/RJ,383

## Mês 6

In [59]:
mes = 6
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [60]:
scrap = pd.read_html(url)

In [61]:
df6 = pd.DataFrame(scrap[0])

In [62]:
df6.drop(df6.tail(3).index, inplace = True)

In [63]:
df6.drop(df6.head(2).index, inplace = True)

In [64]:
new_header = df6.iloc[0]
df6 = df6[1:]
df6.columns = new_header

In [65]:
df6 = df6.assign(MES = '{}'.format(mes))

In [66]:
df6 = df6.assign(ANO = '{}'.format(ano))

In [67]:
df6 = df6.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [68]:
df6 = df6.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [69]:
df6

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,67.457,032,012,000,000,000,000,002,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
4,Angra dos Reis,13016,44.333,059,025,000,000,000,000,004,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
5,Araruama,13017,26.510,075,025,000,000,000,000,017,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
6,Arraial do Cabo,13019,15.077,127,031,000,000,000,000,005,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
7,Arsenal,13020,50.885,050,031,000,000,000,000,006,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,28.044,042,012,000,000,000,000,001,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.246,087,029,000,000,000,000,000,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
82,Bom Jardim,16393,21.768,097,033,000,000,000,000,006,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
83,Retiro Saudoso,16394,61.158,040,024,000,000,000,000,015,...,000,000,000,000,000,000,6,2021,Enel/RJ,383
84,Areal,16395,21.629,125,058,000,000,000,000,033,...,000,000,000,000,000,000,6,2021,Enel/RJ,383

## Mês 7

In [70]:
mes = 7
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [71]:
scrap = pd.read_html(url)

In [72]:
df7 = pd.DataFrame(scrap[0])

In [73]:
df7.drop(df7.tail(3).index, inplace = True)

In [74]:
df7.drop(df7.head(2).index, inplace = True)

In [75]:
new_header = df7.iloc[0]
df7 = df7[1:]
df7.columns = new_header

In [76]:
df7 = df7.assign(MES = '{}'.format(mes))

In [77]:
df7 = df7.assign(ANO = '{}'.format(ano))

In [78]:
df7 = df7.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [79]:
df7 = df7.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [80]:
df7

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,67.184,041,019,000,000,000,000,001,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
4,Angra dos Reis,13016,44.368,044,025,000,000,000,000,010,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
5,Araruama,13017,26.505,054,025,000,000,000,000,002,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
6,Arraial do Cabo,13019,15.054,187,068,000,000,000,000,015,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
7,Arsenal,13020,50.939,033,012,000,000,000,000,002,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,28.059,019,006,000,000,000,000,004,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.276,060,022,000,000,000,000,019,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
82,Bom Jardim,16393,21.806,076,058,000,000,000,000,014,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
83,Retiro Saudoso,16394,61.356,040,026,000,000,000,000,022,...,000,000,000,000,000,000,7,2021,Enel/RJ,383
84,Areal,16395,21.706,147,065,000,000,000,000,020,...,000,000,000,000,000,000,7,2021,Enel/RJ,383

## Mês 8

In [81]:
mes = 8
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [82]:
scrap = pd.read_html(url)

In [83]:
df8 = pd.DataFrame(scrap[0])

In [84]:
df8.drop(df8.tail(3).index, inplace = True)

In [85]:
df8.drop(df8.head(2).index, inplace = True)

In [86]:
new_header = df8.iloc[0]
df8 = df8[1:]
df8.columns = new_header

In [87]:
df8 = df8.assign(MES = '{}'.format(mes))

In [88]:
df8 = df8.assign(ANO = '{}'.format(ano))

In [89]:
df8 = df8.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [90]:
df8 = df8.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [91]:
df8

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,66.815,049,023,000,000,000,000,002,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
4,Angra dos Reis,13016,43.881,076,083,000,000,000,000,004,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
5,Araruama,13017,26.461,117,074,000,000,000,000,008,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
6,Arraial do Cabo,13019,14.971,067,019,000,000,000,000,003,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
7,Arsenal,13020,50.660,037,026,000,000,000,000,001,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,27.949,055,053,000,000,000,000,008,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.210,034,012,000,000,000,000,003,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
82,Bom Jardim,16393,21.799,065,017,000,000,000,000,007,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
83,Retiro Saudoso,16394,61.302,031,017,000,000,000,000,010,...,000,000,000,000,000,000,8,2021,Enel/RJ,383
84,Areal,16395,21.651,137,067,000,000,000,000,026,...,000,000,000,000,000,000,8,2021,Enel/RJ,383

## Mês 9

In [92]:
mes = 9
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [93]:
scrap = pd.read_html(url)

In [94]:
df9 = pd.DataFrame(scrap[0])

In [95]:
df9.drop(df9.tail(3).index, inplace = True)

In [96]:
df9.drop(df9.head(2).index, inplace = True)

In [97]:
new_header = df9.iloc[0]
df9 = df9[1:]
df9.columns = new_header

In [98]:
df9 = df9.assign(MES = '{}'.format(mes))

In [99]:
df9 = df9.assign(ANO = '{}'.format(ano))

In [100]:
df9 = df9.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [101]:
df9 = df9.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [102]:
df9

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,65.824,198,066,000,000,000,000,001,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
4,Angra dos Reis,13016,43.211,076,038,000,000,000,000,002,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
5,Araruama,13017,26.284,228,131,000,000,060,100,002,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
6,Arraial do Cabo,13019,14.961,242,170,000,000,054,100,003,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
7,Arsenal,13020,49.931,329,075,000,000,000,000,002,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,27.652,094,041,000,000,000,000,001,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.169,079,132,000,000,000,000,012,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
82,Bom Jardim,16393,21.753,252,229,000,000,084,188,005,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
83,Retiro Saudoso,16394,60.977,050,024,000,000,000,000,019,...,000,000,000,000,000,000,9,2021,Enel/RJ,383
84,Areal,16395,21.633,558,153,000,000,000,000,009,...,000,000,000,000,000,000,9,2021,Enel/RJ,383

## Mês 10

In [103]:
mes = 10
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [104]:
scrap = pd.read_html(url)

In [105]:
df10 = pd.DataFrame(scrap[0])

In [106]:
df10.drop(df10.tail(3).index, inplace = True)

In [107]:
df10.drop(df10.head(2).index, inplace = True)

In [108]:
new_header = df10.iloc[0]
df10 = df10[1:]
df10.columns = new_header

In [109]:
df10 = df10.assign(MES = '{}'.format(mes))

In [110]:
df10 = df10.assign(ANO = '{}'.format(ano))

In [111]:
df10 = df10.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [112]:
df10 = df10.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [113]:
df10

2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,MES,ANO,DISTRIBUIDORA,COD_DISTRIBUIDORA
3,Alcantara,13015,64.754,048,022,000,000,000,000,000,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
4,Angra dos Reis,13016,43.059,110,067,000,000,000,000,001,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
5,Araruama,13017,26.147,082,037,000,000,000,000,004,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
6,Arraial do Cabo,13019,14.995,075,019,000,000,000,000,002,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
7,Arsenal,13020,49.201,079,024,000,000,000,000,003,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Neves,16391,27.432,046,019,000,000,000,000,003,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
81,Cachoeira de Macacu,16392,16.163,067,027,000,000,000,000,000,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
82,Bom Jardim,16393,21.685,241,093,000,000,000,000,006,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
83,Retiro Saudoso,16394,61.091,052,021,000,000,000,000,012,...,000,000,000,000,000,000,10,2021,Enel/RJ,383
84,Areal,16395,21.527,428,105,000,000,000,000,006,...,000,000,000,000,000,000,10,2021,Enel/RJ,383

## Mês 11

In [114]:
mes = 11
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [115]:
scrap = pd.read_html(url)

In [116]:
df11 = pd.DataFrame(scrap[0])

In [117]:
df11.drop(df11.tail(3).index, inplace = True)

In [118]:
df11.drop(df11.head(2).index, inplace = True)

In [119]:
new_header = df11.iloc[0]
df11 = df11[1:]
df11.columns = new_header

In [120]:
df11 = df11.assign(MES = '{}'.format(mes))

In [121]:
df11 = df11.assign(ANO = '{}'.format(ano))

In [122]:
df11 = df11.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [123]:
df11 = df11.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [124]:
df11

Empty DataFrame
Columns: [CONJUNTO, CÓDIGO, Nº DE CONSUMIDORES, DECTOT, FECTOT, DECXP, FECXP, DECXN, FECXN, DECIP, FECIP, DECIND, FECIND, DECINE, FECINE, DECINC, FECINC, DECINO, FECINO, DECIPC, FECIPC, DECXPC, FECXPC, DECXNC, FECXNC, MES, ANO, DISTRIBUIDORA, COD_DISTRIBUIDORA]
Index: []

[0 rows x 29 columns]

## Mês 12

In [125]:
mes = 12
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [126]:
scrap = pd.read_html(url)

In [127]:
df12 = pd.DataFrame(scrap[0])

In [128]:
df12.drop(df12.tail(3).index, inplace = True)

In [129]:
df12.drop(df12.head(2).index, inplace = True)

In [130]:
new_header = df12.iloc[0]
df12 = df12[1:]
df12.columns = new_header

In [131]:
df12 = df12.assign(MES = '{}'.format(mes))

In [132]:
df12 = df12.assign(ANO = '{}'.format(ano))

In [133]:
df12 = df12.assign(DISTRIBUIDORA = '{}'.format(nome_distribuidora))

In [134]:
df12 = df12.assign(COD_DISTRIBUIDORA = '{}'.format(distribuidora))

In [135]:
df12

Empty DataFrame
Columns: [CONJUNTO, CÓDIGO, Nº DE CONSUMIDORES, DECTOT, FECTOT, DECXP, FECXP, DECXN, FECXN, DECIP, FECIP, DECIND, FECIND, DECINE, FECINE, DECINC, FECINC, DECINO, FECINO, DECIPC, FECIPC, DECXPC, FECXPC, DECXNC, FECXNC, MES, ANO, DISTRIBUIDORA, COD_DISTRIBUIDORA]
Index: []

[0 rows x 29 columns]

## Concatenação e exportação dos dados

In [136]:
dfinal = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12])

In [137]:
dfinal.to_csv('Dados_Enel_2021.csv'.format(nome_distribuidora, ano),index=False, encoding='utf-8')