In [1]:
import pandas as pd

In [2]:
mes = 1
ano = 2021
distribuidora = 383
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [3]:
scrap = pd.read_html('https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes=1&ano=2017&regiao=SE&distribuidora=383&tipo=d')

In [4]:
df1 = pd.DataFrame(scrap[0])

In [5]:
df1.drop(df1.tail(3).index,inplace=True)

In [6]:
df1.drop(df1.head(2).index,inplace=True)

In [7]:
df1

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,DECINC,FECINC,DECINO,FECINO,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC
3,Alcantara,13015,72.743,176,192,000,000,000,000,012,...,000,000,000,000,000,000,000,000,000,000
4,Angra dos Reis,13016,44.017,482,195,000,000,000,000,020,...,111,012,000,000,000,000,000,000,000,000
5,Araruama,13017,24.691,148,066,000,000,000,000,019,...,000,000,000,000,000,000,000,000,000,000
6,Areal,13018,15.494,697,263,000,000,000,000,097,...,072,046,000,000,000,000,000,000,000,000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Vila Verde,13095,21.347,160,154,000,000,000,000,019,...,001,000,000,000,000,000,000,000,000,000
84,Zona Sul,13096,48.105,324,247,000,000,000,000,024,...,042,010,000,000,000,000,000,000,000,000
85,Cedaema,13097,3.545,915,348,000,000,000,000,008,...,046,003,000,000,000,000,000,000,000,000
86,Val de Palmas,13098,25.773,144,065,000,000,000,000,013,...,021,018,000,000,000,000,000,000,000,000
87,Neves,13099,21.622,178,114,000,000,000,000,006,...,000,000,000,000,000,000,000,000,000,000

In [8]:
df1 = df1.assign(data = '{}/{}'.format(mes, ano))

In [9]:
mes = 2
ano = 2021
distribuidora = 383
 
# link para conseguir os dados necessários
url = "https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes={}&ano={}&regiao=SE&distribuidora={}&tipo=d".format(mes, ano, distribuidora)

In [10]:
scrap = pd.read_html('https://www2.aneel.gov.br/aplicacoes/indicadores_de_qualidade/decFecSegMensal.cfm?mes=1&ano=2017&regiao=SE&distribuidora=383&tipo=d')

In [11]:
df2 = pd.DataFrame(scrap[0])

In [12]:
df2.drop(df2.tail(3).index,inplace=True)

In [13]:
df2.drop(df2.head(2).index,inplace=True)

In [14]:
df2 = df2.assign(data = '{}/{}'.format(mes, ano))

In [15]:
pd.concat([df1, df2])

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,data
2,CONJUNTO,CÓDIGO,Nº DE CONSUMIDORES,DECTOT,FECTOT,DECXP,FECXP,DECXN,FECXN,DECIP,...,FECINC,DECINO,FECINO,DECIPC,FECIPC,DECXPC,FECXPC,DECXNC,FECXNC,1/2021
3,Alcantara,13015,72.743,176,192,000,000,000,000,012,...,000,000,000,000,000,000,000,000,000,1/2021
4,Angra dos Reis,13016,44.017,482,195,000,000,000,000,020,...,012,000,000,000,000,000,000,000,000,1/2021
5,Araruama,13017,24.691,148,066,000,000,000,000,019,...,000,000,000,000,000,000,000,000,000,1/2021
6,Areal,13018,15.494,697,263,000,000,000,000,097,...,046,000,000,000,000,000,000,000,000,1/2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Vila Verde,13095,21.347,160,154,000,000,000,000,019,...,000,000,000,000,000,000,000,000,000,2/2021
84,Zona Sul,13096,48.105,324,247,000,000,000,000,024,...,010,000,000,000,000,000,000,000,000,2/2021
85,Cedaema,13097,3.545,915,348,000,000,000,000,008,...,003,000,000,000,000,000,000,000,000,2/2021
86,Val de Palmas,13098,25.773,144,065,000,000,000,000,013,...,018,000,000,000,000,000,000,000,000,2/2021
87,Neves,13099,21.622,178,114,000,000,000,000,006,...,000,000,000,000,000,000,000,000,000,2/2021